name: mv_bookshelf
description: The offical MV Bookshelf App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  google_fonts: ^2.1.0
  firebase_core: ^1.2.0
  path_provider: ^2.0.2
  syncfusion_flutter_pdfviewer: ^19.2.48-beta
  firebase_database: ^7.0.0
  auto_size_text: ^2.1.0
  shared_preferences: ^2.0.6
  flutter_launcher_icons: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Mv Bookshelf"

flutter_icons:
  android: "launcher_icon"
  image_path_android: "assets/logo_transparent.png"
  image_path_ios: "assets/bookshelf_logo.png"
  remove_alpha_ios: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/